In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv("labeled_data.csv.zip")

# Extract Offensive Language and Neither
non_hate_df = df[df['class'].isin([1, 2])]

# Save the extracted dataset
non_hate_df.to_csv("non_hate_speech_dataset.csv", index=False)

print("Total Non-Hate Samples:", len(non_hate_df))
print(non_hate_df['class'].value_counts())

Total Non-Hate Samples: 23353
class
1    19190
2     4163
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("labeled_data.csv.zip")

# Keep only Offensive Language and Neither
non_hate_df = df[df['class'].isin([1, 2])].copy()

# Convert both to Non-Hate (0)
non_hate_df['class'] = 0

# Keep only the required columns
non_hate_df = non_hate_df[['tweet', 'class']]

# Save dataset
non_hate_df.to_csv("non_hate_speech_dataset.csv", index=False)

print(non_hate_df.head())
print(non_hate_df['class'].value_counts())

                                               tweet  class
0  !!! RT @mayasolovely: As a woman you shouldn't...      0
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...      0
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...      0
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...      0
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...      0
class
0    23353
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Load your main dataset
main_df = pd.read_csv("merged_hate_speech_dataset.csv")

# Load Davidson dataset
davidson_df = pd.read_csv("labeled_data.csv.zip")

# Extract only Offensive Language and Neither
non_hate_df = davidson_df[davidson_df["class"].isin([1, 2])].copy()

# Keep only the tweet column
non_hate_df = non_hate_df[["tweet"]]

# Rename to match main dataset
non_hate_df.rename(columns={"tweet": "text"}, inplace=True)

# Assign Non-Hate label
non_hate_df["label"] = 0

# Merge with the main dataset
final_df = pd.concat([main_df, non_hate_df], ignore_index=True)

# Remove missing values
final_df.dropna(subset=["text"], inplace=True)

# Remove duplicate texts
final_df.drop_duplicates(subset=["text"], inplace=True)

# Shuffle the dataset
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Save
final_df.to_csv("final_hate_speech_dataset.csv", index=False)

# Display statistics
print("Final Dataset Shape:", final_df.shape)
print("\nLabel Distribution:")
print(final_df["label"].value_counts())

Final Dataset Shape: (67288, 2)

Label Distribution:
label
0    41010
1    26278
Name: count, dtype: int64

In [ ]:
final_df.to_csv("final_hate_speech_dataset.csv", index=False, encoding="utf-8")

In [ ]:
from google.colab import files

# Save the dataset
final_df.to_csv("final_hate_speech_dataset.csv", index=False)

# Download it to your laptop
files.download("final_hate_speech_dataset.csv")

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv("/content/final_hate_speech_dataset.csv")

# Separate classes
hate = df[df['label'] == 1]
non_hate = df[df['label'] == 0]

print("Original Distribution:")
print(df['label'].value_counts())

# Randomly sample Non-Hate class
non_hate_sampled = non_hate.sample(n=32118, random_state=42)

# Combine with all Hate samples
balanced_df = pd.concat([hate, non_hate_sampled])

# Shuffle the dataset
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Save the new dataset
balanced_df.to_csv("/content/final_hate_speech_dataset_55_45.csv", index=False)

print("\nNew Distribution:")
print(balanced_df['label'].value_counts())

print("\nPercentage Distribution:")
print((balanced_df['label'].value_counts(normalize=True) * 100).round(2))

print("\nNew Dataset Shape:")
print(balanced_df.shape)

Original Distribution:
label
0    41010
1    26278
Name: count, dtype: int64

New Distribution:
label
0    32118
1    26278
Name: count, dtype: int64

Percentage Distribution:
label
0    55.0
1    45.0
Name: proportion, dtype: float64

New Dataset Shape:
(58396, 2)

In [ ]:
from google.colab import files
files.download("/content/final_hate_speech_dataset_55_45.csv")

In [ ]:
from datasets import load_dataset

ds = load_dataset("google/civil_comments")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/7.73k [00:00<?, ?B/s]

data/train-00000-of-00002.parquet:   0%|          | 0.00/194M [00:00<?, ?B/s]

data/train-00001-of-00002.parquet:   0%|          | 0.00/187M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/20.8M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1804874 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/97320 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/97320 [00:00<?, ? examples/s]

In [ ]:
from datasets import load_dataset

# Load dataset
ds = load_dataset("google/civil_comments")

# Convert to pandas
train_df = ds["train"].to_pandas()
val_df = ds["validation"].to_pandas()
test_df = ds["test"].to_pandas()

# Save as CSV
train_df.to_csv("civil_comments_train.csv", index=False)
val_df.to_csv("civil_comments_validation.csv", index=False)
test_df.to_csv("civil_comments_test.csv", index=False)

In [ ]:
from google.colab import files

files.download("civil_comments_train.csv")
files.download("civil_comments_validation.csv")
files.download("civil_comments_test.csv")

In [ ]:
import pandas as pd

train = pd.read_csv("/content/civil_comments_train.csv")
print("Train Loaded")

Train Loaded

In [ ]:
validation = pd.read_csv("/content/civil_comments_validation.csv")
print("Validation Loaded")

Validation Loaded

In [ ]:
test = pd.read_csv("/content/civil_comments_test.csv")
print("Test Loaded")

Test Loaded

In [ ]:
import pandas as pd

# Load datasets
train = pd.read_csv("/content/civil_comments_train.csv", engine='python', on_bad_lines='skip')
validation = pd.read_csv("/content/civil_comments_validation.csv", engine='python', on_bad_lines='skip')
test = pd.read_csv("/content/civil_comments_test.csv", engine='python', on_bad_lines='skip')

# Merge
civil_comments = pd.concat(
    [train, validation, test],
    ignore_index=True
)

# Remove duplicate comments
civil_comments.drop_duplicates(subset="text", inplace=True)

# Reset index
civil_comments.reset_index(drop=True, inplace=True)

# Display information
print("Merged Shape:", civil_comments.shape)
print("\nColumns:")
print(civil_comments.columns)

# Save merged dataset
civil_comments.to_csv("/content/civil_comments_merged.csv", index=False)

print("\nMerged dataset saved successfully!")

Merged Shape: (1971914, 8)

Columns:
Index(['text', 'toxicity', 'severe_toxicity', 'obscene', 'threat', 'insult',
       'identity_attack', 'sexual_explicit'],
      dtype='object')

Merged dataset saved successfully!

In [ ]:
civil_comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1971914 entries, 0 to 1971913
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   text             object
 1   toxicity         float64
 2   severe_toxicity  float64
 3   obscene          float64
 4   threat           float64
 5   insult           float64
 6   identity_attack  float64
 7   sexual_explicit  float64
dtypes: float64(7), object(1)
memory usage: 120.4+ MB

In [ ]:
civil_comments.head()

,text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit
0,"This is so cool. It's like, 'would you want yo...",0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
1,Thank you!! This would make my life a lot less...,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
2,This is such an urgent design problem; kudos t...,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
3,Is this something I'll be able to install on m...,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
4,haha you guys are a bunch of losers.,0.893617,0.021277,0.0,0.0,0.87234,0.021277,0.0

In [ ]:
print(civil_comments.shape)

(1971914, 8)

In [ ]:
print(civil_comments.shape)

(1971914, 8)

In [ ]:
civil_comments.isnull().sum()

text               1
toxicity           0
severe_toxicity    0
obscene            0
threat             0
insult             0
identity_attack    0
sexual_explicit    0
dtype: int64

In [ ]:
print(civil_comments.columns.tolist())

['text', 'toxicity', 'severe_toxicity', 'obscene', 'threat', 'insult', 'identity_attack', 'sexual_explicit']

In [ ]:
civil_comments.head()

,text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit
0,"This is so cool. It's like, 'would you want yo...",0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
1,Thank you!! This would make my life a lot less...,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
2,This is such an urgent design problem; kudos t...,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
3,Is this something I'll be able to install on m...,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0
4,haha you guys are a bunch of losers.,0.893617,0.021277,0.0,0.0,0.87234,0.021277,0.0

In [ ]:
civil_comments["label"] = (
    (civil_comments["identity_attack"] >= 0.5) |
    (civil_comments["threat"] >= 0.5) |
    (civil_comments["severe_toxicity"] >= 0.7)
).astype(int)

In [ ]:
print(civil_comments["label"].value_counts())

label
0    1952933
1      18981
Name: count, dtype: int64

In [ ]:
civil_comments = civil_comments[["text", "label"]]

In [ ]:
civil_comments.to_csv(
    "/content/civil_comments_binary.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!

In [ ]:
import pandas as pd

# Separate classes
hate = civil_comments[civil_comments["label"] == 1]
non_hate = civil_comments[civil_comments["label"] == 0]

# Randomly sample non-hate examples
non_hate = non_hate.sample(n=40000, random_state=42)

# Merge
civil_balanced = pd.concat([hate, non_hate], ignore_index=True)

# Shuffle
civil_balanced = civil_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(civil_balanced["label"].value_counts())

label
0    40000
1    18981
Name: count, dtype: int64

In [ ]:
existing = pd.read_csv("/content/merged_hate_speech_dataset.csv")

final_dataset = pd.concat(
    [existing, civil_balanced],
    ignore_index=True
)

# Remove duplicate texts
final_dataset = final_dataset.drop_duplicates(subset="text")

# Shuffle
final_dataset = final_dataset.sample(frac=1, random_state=42).reset_index(drop=True)

print(final_dataset["label"].value_counts())

# Save
final_dataset.to_csv(
    "/content/final_english_hate_dataset.csv",
    index=False
)

label
0    57957
1    45259
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Load your main dataset
main_df = pd.read_csv("/content/final_hate_speech_dataset.csv")

# civil_balanced should already exist from the previous step
# If not, load the balanced Civil Comments CSV instead.
# civil_balanced = pd.read_csv("/content/civil_comments_balanced.csv")

# Merge
merged_df = pd.concat([main_df, civil_balanced], ignore_index=True)

# Remove duplicate texts
merged_df = merged_df.drop_duplicates(subset="text")

# Shuffle
merged_df = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Check distribution
print("Final Dataset Shape:", merged_df.shape)
print("\nLabel Distribution:")
print(merged_df["label"].value_counts())

# Save
merged_df.to_csv("/content/final_merged_hate_speech_dataset.csv", index=False)

print("Dataset saved successfully!")

Final Dataset Shape: (114837, 2)

Label Distribution:
label
0.0    74070
1.0    40766
Name: count, dtype: int64
Dataset saved successfully!

In [ ]:
# Find texts that have both labels
conflicts = (
    merged_df.groupby("text")["label"]
    .nunique()
)

conflicting_texts = conflicts[conflicts > 1]

print("Conflicting texts:", len(conflicting_texts))

Conflicting texts: 0

In [ ]:
from google.colab import files

files.download("/content/final_merged_hate_speech_dataset.csv")

In [ ]:
# ============================================
# Hate Speech Dataset Cleaning Pipeline
# Run this in Colab after uploading your CSV
# ============================================

import pandas as pd
import re

# --- 1. Load ---
df = pd.read_csv('final_merged_hate_speech_dataset.csv')
print(f"Original shape: {df.shape}")

# --- 2. Drop missing labels ---
df = df.dropna(subset=['label', 'text']).copy()
df['label'] = df['label'].astype(int)  # 0.0/1.0 -> 0/1
print(f"After dropping NaNs: {df.shape}")

# --- 3. Normalize social media artifacts (consistent preprocessing) ---
def normalize_text(text):
    text = str(text)

    # Unify placeholder style: turn raw mentions into <user>
    text = re.sub(r'@\w+', '<user>', text)

    # Turn URLs into <url>
    text = re.sub(r'http\S+|www\.\S+', '<url>', text)

    # Strip leading "RT" retweet marker
    text = re.sub(r'^RT\s*[:]?\s*', '', text, flags=re.IGNORECASE)

    # Collapse repeated whitespace/newlines
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df['text_clean'] = df['text'].apply(normalize_text)

# --- 4. Flag decorative/spam junk (heavy non-ASCII ratio, low real-word content) ---
def junk_score(text):
    if len(text) == 0:
        return 1.0
    non_ascii = sum(1 for c in text if ord(c) > 127)
    return non_ascii / len(text)

df['non_ascii_ratio'] = df['text_clean'].apply(junk_score)
junk_mask = df['non_ascii_ratio'] > 0.3  # tune threshold as needed
print(f"\nFlagged as likely junk/spam (>30% non-ASCII): {junk_mask.sum()} rows")
df = df[~junk_mask].copy()

# --- 5. Deduplicate (exact + case-insensitive near-duplicates) ---
before = len(df)
df['text_norm'] = df['text_clean'].str.lower().str.strip()
df = df.drop_duplicates(subset=['text_norm'], keep='first').copy()
print(f"Removed {before - len(df)} duplicate/near-duplicate rows")

# --- 6. Handle very short texts (decide: keep, flag, or drop) ---
df['word_count'] = df['text_clean'].str.split().apply(len)
very_short = df['word_count'] <= 2
print(f"\nVery short texts (<=2 words): {very_short.sum()}")
print("Sample:", df[very_short][['text_clean', 'label']].head(5).to_dict('records'))

# OPTION A: keep them but flag for review
df['is_very_short'] = very_short

# OPTION B: drop them entirely — uncomment if you decide context-free
# single words/slurs aren't useful for your use case
# df = df[~very_short].copy()

# --- 7. Final cleanup: drop helper columns, keep clean text as primary ---
df_final = df[['text_clean', 'label']].rename(columns={'text_clean': 'text'})
df_final = df_final.reset_index(drop=True)

# --- 8. Stats before/after ---
print(f"\n{'='*50}")
print(f"FINAL DATASET: {df_final.shape}")
print(f"Class balance:\n{df_final['label'].value_counts(normalize=True)}")
print(f"{'='*50}")

# --- 9. Save ---
df_final.to_csv('hate_speech_cleaned.csv', index=False)
print("\nSaved as hate_speech_cleaned.csv")

# Optional: download in Colab
from google.colab import files
files.download('hate_speech_cleaned.csv')

Original shape: (114837, 2)
After dropping NaNs: (114836, 2)

Flagged as likely junk/spam (>30% non-ASCII): 5 rows
Removed 1440 duplicate/near-duplicate rows

Very short texts (<=2 words): 926
Sample: [{'text_clean': 'Fa-reak.', 'label': 0}, {'text_clean': 'Legalize Nationwide!', 'label': 0}, {'text_clean': 'where? were?', 'label': 0}, {'text_clean': 'ghetto black', 'label': 0}, {'text_clean': 'fucking cunts', 'label': 1}]

==================================================
FINAL DATASET: (113391, 2)
Class balance:
label
0    0.645607
1    0.354393
Name: proportion, dtype: float64
==================================================

Saved as hate_speech_cleaned.csv